Repository secretkeylabs/xverse-core, pull requests merged in 2024-02, with the labels that each got.

#367 Improve “TooMuchChaining” error message when broadcasting Stacks tx
  transactions/stx.ts
Labels: patch

#363 Added web manifest utils
  connect/index.ts
  connect/manifest.ts
  tests/connect/manifest.test.ts
Labels: minor

#362 feat: spam tokens API function
  api/xverse.ts
Labels: minor

#346 Refactor transaction logic for ease of use
  currency/index.ts
  tests/transactions/bitcoin/actionProcessors.sendBtc.test.ts
  tests/transactions/bitcoin/actionProcessors.sendUtxo.test.ts
  tests/transactions/bitcoin/actionProcessors.splitUtxo.test.ts
  tests/transactions/bitcoin/enhancedTransaction.test.ts
  tests/transactions/bitcoin/index.test.ts
  transactions/bitcoin/actionProcessors.ts
  transactions/bitcoin/context.ts
  transactions/bitcoin/enhancedTransaction.ts
  transactions/bitcoin/index.ts
  transactions/bitcoin/types.ts
Labels: major

#287 Featured Apps api utils
  api/xverse.ts
  types/api/xverse/appConfig.ts
  types/index.ts
Labels: enhancement
