Repository secretkeylabs/xverse-core, pull requests merged in 2024-01, with the labels that each got.

#337 bug-fix/rbf-support-custom-seed-handler
  transactions/rbf.ts
Labels: mobile 1.25.0

#348 Update the RbfTransaction class constructor
  transactions/rbf.ts
Labels: mobile 1.25.0, breaking change

#355 Remove ledger fields from final PSBT
  transactions/bitcoin/context.ts
Labels: Extension 0.29.0

#356 feat: get brc-20 tokens API
  api/xverse.ts
  types/api/stacks/transaction.ts
  types/api/xverse/coins.ts
Labels: Extension 0.29.0
